#abc=("computer")
#print(abc[2])
#starting position : ednding positin+1
#abc=("computer")
#print(abc[3:3])
#abc=("computer")
#print(len(abc))
#print(abc[0:7+1])
#abc=("computer")
#print(abc[:-5])
#abc=("computer")
#print(abc[0:8])
#abc=("com puter")
#print(abc[0:5]+abc[5:10])
#abc=("computer")
#print(abc.find("p"))
#abc=("today your class will stop after few days ago strted my class")
#y=(abc.find("will"))
#print(abc[y:])
#print(abc[:y])
#print(abc[0:y])
#print(abc[y:55])
